return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = "VeryLazy",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-context",
    },
    config = function()
      local config = require("nvim-treesitter.configs")
      config.setup({
        additional_vim_regex_highlighting = false,
        auto_install = true,
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
          "lua",
          "luadoc",
          "vim",
          "vimdoc",
          "javascript",
          "markdown",
          "go",
          "gomod",
          "gosum",
          "python",
          "typescript",
          "dockerfile",
          "yaml",
          "html",
          "bash",
          "nginx",
          "regex",
          "sql",
          "json",
          "sql",
          "nginx",
          "csv",
          "toml",
          "git_config",
          "helm",
          "http",
          "jq",
          "regex",
          "rust",
          "terraform",
          "zig",
          "markdown_inline",
        },
      })
    end,
  },
}
